[package]
name = 'girouette'
version = '0.3.0-dev'
authors = ['Antoine Gourlay <antoine@gourlay.fr>']
edition = '2018'

[dependencies]
chrono = '0.4'
directories = '2'
failure = '0.1'
humantime = '2'
log = '0.4'
pretty_env_logger = '0.4'
termcolor = '1.1'
reqwest = '0.10'
serde_json = '1'

[dependencies.structopt]
version = '0.3'
default-features = false
features = ['suggestions']

[dependencies.config]
version = '0.10'
default-features = false
features = ['yaml']

[dependencies.serde]
version = '1'
features = ['derive']

[dependencies.tokio]
version = '0.2'
features = ['rt-core']

[profile.release]
lto = true
