[package]
name = 'girouette'
version = "0.2.1"
authors = ['Antoine Gourlay <antoine@gourlay.fr>']
edition = '2018'

[dependencies]
chrono = "0.4"
directories = "2"
failure = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
termcolor = "1.1"
reqwest = "0.10"
serde_json = "1"
structopt = "0.3"

[dependencies.config]
version = "0.10"
features = ["yaml"]

[dependencies.serde]
version = '1'
features = ['derive']

[dependencies.tokio]
version = '0.2'
features = ['full']

[profile.release]
lto = true
