[package]
name = 'weather'
version = "0.1.0"
authors = ['Antoine Gourlay <antoine@gourlay.fr>']
edition = '2018'

[dependencies]
chrono = "0.4"
termcolor = "1.1"
structopt = "0.3"

[dependencies.serde]
version = '1'
features = ['derive']

[dependencies.reqwest]
version = '0.10'
features = ['json']

[dependencies.tokio]
version = '0.2'
features = ['full']
