# Config file for girouette

# OpenWeather API key
#
# This is a default key for girouette. It is rate-limited, so
# get a free API key over at https://openweathermap.org/
key: "467cf0f1a1d612944d2da01c515c6f26"

# Location to query
#
#location = "Dubai"
#location = "53.258,3.114"
location: "London, UK"

# Separator text between entries
#
# defaults to two whitespace charaters "  "
#separator: " | "

# Units to use when displaying temperatures and speeds.
# Possible units are:
#
#  - metric: Celsius temperatures and kilometers/hour speeds (the default),
#
#  - imperial: Fahrenheit temperatures and miles/hour speeds,
#
#  - standard: Kelvin temperatures and meters/second speeds.
#units: "metric"

# Caching of API responses
#
# Value can be a duration ("1h", "2 days", "10min") or "none" to disable it
cache: "5m"

# Time to wait for a response from Openweather
#
# Value can be a duration ("1h", "2 days", "10min"), defaults to "10s".
#timeout: "10s"

# Language for location names, weather descriptions and date/time formatting.
#
# Possible values are of the form 'aa_AA' like 'en_US' or 'fr_FR'. Note that
# OpenWeather only supports a subset of all valid LANG values.
#language: "ja_JP"

# Background style for the whole bar
#
# All other styles support the same options.
# All colors can be either:
#  - a color name (black, blue, green, red, cyan, magenta, yellow, white)
#    example: "yellow"
#  - an integer between 0 and 255 representing an ANSI color code
#    example: 122
#  - an hexadecimal color code
#    example: "#002b3f"
#  - a triple of integer representing an RGB color
#    example: [15, 55, 84]
base_style:
  # Background color
  bg: "#1b1d1e"
  # Foreground color
  fg: "#f8f8f2"
  # Bold text
  #bold: false
  # Intense text
  #intense: false
  # Underline text (not supported in all terminals)
  #underline: false
  # Italic text (not supported in all terminals)
  #italic: false

# Display mode supported by the terminal emulator:
# - "ascii"
#   Only use ASCII charaters. Icons will be very limited or even inexistant.
#
# - "unicode"
#   Use standard Unicode characters. This will use the somewhat limited list of
#   weather related icons in Unicode. This is the default.
#
# - "nerd_fonts"
#   Use the weather icons provided as part of the Nerd Fonts package.
#   The provides the most specific and best-looking icons for weather, but must
#   be installed first.
#
#display_mode: "unicode"

# Segments to display
segments:
  - instant:
      style:
        fg: "#fd971f"
      date_format: "%R"
  - location_name:
      style:
        fg: "#ae81ff"
        intense: true
  - weather_icon:
      style:
        fg: "#c4be89"
        intense: true
  - weather_description:
      style:
        fg: "#c4be89"
  - temperature
  - rain:
      style:
        fg: 45
  - snow:
      style:
        fg: 45
  - wind_speed
  - hourly_forecast