dev-version-ext = "dev"
post-release-commit-message = "release: bumping to {{next_version}} after {{version}} release"
pre-release-commit-message = "release: {{version}}"
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}"},
  {file="CHANGELOG.md", search="TBD", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - TBD"},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gourlaysama/weather/compare/{{tag_name}}...HEAD"},
  {file="README.md", search="-b v.+\n\\$", replace="-b v{{version}}\n$"},
  {file="README.md", search="--version\nweather .+", replace="--version\nweather {{version}}"},
]
sign-commit = true